### ISSUE TITLE
MVP Feature: User can start a chess game in multiplayer

### ISSUE THREAD

**Issue by josephtnguyen** [josephtnguyen/straight-up-chess#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can start a chess game in multiplayer.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

From the homescreen, the user can open a page for creating multiplayer chess games.  On the page, the user can create a post for a new chess game.  While they wait for someone to accept, they will be moved to the game.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/59109937/126215962-f85a1605-018b-4f53-8802-e1ff66896a65.png)
![image](https://user-images.githubusercontent.com/59109937/126216036-b6ef36a0-4852-49c1-98e4-e45db58d7b6d.png)
![image](https://user-images.githubusercontent.com/59109937/126216062-abc1867e-14df-487a-aef1-2b5f1aa57258.png)
![image](https://user-images.githubusercontent.com/59109937/126216083-e14bc6e4-8347-4b76-8fb5-f1ec56bbd5ea.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Add `schema.sql` with a table for holding posted games

### ☁️ Server

- [x] Add `server/index.js` that receives post game requests
- [x] update `server/index.js` to receive cancel game requests
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a header component
- [x] Create a Home component
- [x] Create a game-mode button component
- [x] Create a Navbar component
- [x] Link the Home option of the Navbar to the Home page
- [x] Create a Join Game component
- [x] Link the Join Game Button  on the Navbar to the Join Game page
- [x] Link the Multiplayer button on the Home page to Join Game page
- [x] Create an add post button component
- [x] Create a Post Form component
- [x] Create a side selection button component
- [x] Add side selection to the Post Form page, updating the form depending on the side picked
- [x] Add a message area to the Post Form page
- [x] Create a cancel button component
- [x] Create a create post component
- [x] Add the cancel and create buttons to the Post Form page
- [x] Link the cancel button to the Join Game page
- [x] Link the add post button to the Post Form page
- [x] Create a Game component that holds a board and gamestate in its state
- [x] Add modules for the board and gamestate
- [x] Create a player palette component
- [x] Render "waiting for challenger" if there is no player info added
- [x] Create a board component that renders the board based on Game.state.board
- [x] Link the create post button to the Game page
- [x] Link the cancel button on the Game page to the Join Game page
- [x] Send a post game request to the server when the create post button is clicked
- [x] Send a delete game request to the server when the create post button is clicked
- [x] Make app desktop responsive

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
