### ISSUE TITLE
MVP Feature: User can play chess on a single device

### ISSUE THREAD

**Issue by josephtnguyen** [josephtnguyen/straight-up-chess#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can play chess on a single device.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On the home page will be a singleplayer option.  When playing in singleplayer, the user will take turns moving either side of the board.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/59109937/126219803-31d6dfcd-7c00-4967-b413-439e76932657.png)
![image](https://user-images.githubusercontent.com/59109937/126219656-0df5f2fe-547e-488b-8bb1-3ce75e9a96de.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Add a 'Singleplayer' button to the Home page
- [x] Create a Singleplayer page
- [x] Adapt the Game page to play on a single device
- [x] Create a Singleplayer Postgame page for victories and forfeits
- [x] Open to the Home page when leaving a singleplayer game

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
