### ISSUE TITLE
MVP Feature: User can view a list of games to join

### ISSUE THREAD

**Issue by josephtnguyen** [josephtnguyen/straight-up-chess#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a list of games to join.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On the Join Game page, posted games will appear as a scrollable list.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/59109937/126216784-baac0d2b-d9a3-4132-9e3e-507108f410ce.png)
![image](https://user-images.githubusercontent.com/59109937/126216814-1deef933-da19-4bc8-9127-ecbf76e2129d.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to get games without an opponent
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a Post component
- [x] Add a scrollable area in the JoinGame page
- [x] Implement a fetch request to get the posted games when opening JoinGame
- [x] Map the fetch response onto the Post component and render it on the JoinGame page
- [x] Update the Post component to reverse the board depending on the side played
- [x] Make sure the scrollable area is desktop responsive

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
