### ISSUE TITLE
MVP Feature: User can join a game

### ISSUE THREAD

**Issue by josephtnguyen** [josephtnguyen/straight-up-chess#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can join a game.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On the Join Game page, clicking on a posted game will let the user join the game.  This will initiate a game between the poster and user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/59109937/126217032-a54f9392-c2e7-45c8-b9d7-1ac0b6bfbac8.png)
![image](https://user-images.githubusercontent.com/59109937/126217108-1377a1b6-a209-439d-bd93-8b83730e5dba.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to update a game with the opponent info
- [x] Import socket.io
- [x] Make an event listener for 'join lobby' to add the socket to the 'lobby' room
- [x] Make an event listener for 'game joined', and emit the same event to the 'lobby' room
- [x] Make an event listener for 'join room' to add the socket to the specified room using gameId
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Connect a socket in ComponentDidMount() of JoinGame page
- [x] Emit a 'join lobby' event in ComponentDidMount() of JoinGame page
- [x] Disconnect the socket event in ComponentDidUnmount() of JoinGame page
- [x] Update Post to send a fetch request to update the selected game when clicking on the post
- [x] Navigate the opponent to specific Game page after the fetch request responds
- [x] Broadcast a 'game joined' event after the fetch
- [x] Send a new fetch request for posted games when receiving a 'game joined' event
- [x] Update Game page to hold an opponent
- [x] Connect a socket in ComponentDidMount() of Game page
- [x] Emit a 'join room' event using gameId after getting the game data on the Game page
- [x] Update Game page to display the correct board based on the Game.state.side
- [x] Render the Game page from the perspective of the challenger

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
