### ISSUE TITLE
Design Update: Chess pieces will transition across the board when moved

### ISSUE THREAD

**Issue by josephtnguyen** [josephtnguyen/straight-up-chess#31]
## ⚙️ Feature

> ##### Which feature is affected by this update?

User can take their turn

## 📐 Plan

> ##### Summary of the technical approach to be taken.

The Board React component will be redone so that the pieces are positioned absolutely above the board instead of within a tile div.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Position every piece 'on top' of the board.
- [x] Give each piece its proper positioning.
- [x] Ensure the position scales with the board.
- [x] Apply the transition property to the pieces.
- [x] Make sure the position is properly displayed for the Game page, when the side is Black.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that don't do anything.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
