### ISSUE TITLE
MVP Feature: User can take their turn

### ISSUE THREAD

**Issue by josephtnguyen** [josephtnguyen/straight-up-chess#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can take their turn.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will be able to play chess.  Selecting a piece will highlight it's move space, and then selecting a highlighted square will move the piece accordingly.  When check, checkmate, or draw occurs, a message will be displayed.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/59109937/126217506-be696112-496d-48a0-9331-ae31ce04b524.png)
![image](https://user-images.githubusercontent.com/59109937/126217536-8b2b2b09-ba96-4cc4-b461-7511b692e3e6.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to include createdAt in the moves table

### ☁️ Server

- [x] Update `server/index.js` to add rows to the "moves" table
- [x] Emit added moves to the corresponding room
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Allow board component to highlight particular tiles
- [x] Highlight a piece's move space when they are selected
- [x] Update isViableMove to not use set prototype
- [x] Unhighlight a piece's move space if anywhere outside their move space is selected
- [x] Move the piece when a highlighted square is selected
- [x] fix en passant in findMoveSpace
- [x] fix draw scan
- [x] When a piece is moved, remove the highlighted squares
- [x] When a piece is moved, post the move to the database and emit the 'move made' to the room
- [x] Update the board and gamestate when a 'move made' event is received
- [x] Make sure a player can only move pieces on their turn
- [x] Update the player palette with killed pieces
- [x] Display Check when appropriate
- [x] Display Checkmate when appropriate, and stop the game
- [x] Display Draw when appropriate, and stop the game
- [x] Allow the player to promote pawns
- [x] Make sure the game page functions in desktop view

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
