### ISSUE TITLE
MVP Feature: User can win the game

### ISSUE THREAD

**Issue by josephtnguyen** [josephtnguyen/straight-up-chess#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can win the game.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When a game concludes, the user will be taken to a post-game page.  From there, they can either return to the Join Game page, or continue observing the board.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/59109937/126217806-a164884a-370a-4cb9-b9c5-04961a28fabc.png)
![image](https://user-images.githubusercontent.com/59109937/126217842-97869d1e-1677-4f11-bdd9-76d917556642.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to contain a winner (NULL, 'black', 'white', or 'draw')

### ☁️ Server

- [x] Update `server/index.js` to update a game row with the winner
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create post game component with players
- [x] Place a trophy next to the winner
- [x] Create resolution component
- [x] Create return to game button
- [x] Close the post game component when return to game is clicked
- [x] Create exit button
- [x] Route the exit button to the JoinGame page
- [x] Make sure the post game page works on desktop view
- [x] Display the post game page only when a game has resolved

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
