### ISSUE TITLE
MVP Feature: User can forfeit the game

### ISSUE THREAD

**Issue by josephtnguyen** [josephtnguyen/straight-up-chess#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can forfeit the game.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can exit the game prematurely, automatically giving the win to their opponent.  This occurs when they explicitly leave using the exit button, or when they navigate away using the menu.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![image](https://user-images.githubusercontent.com/59109937/126218187-aad0f352-f58c-4959-92a6-5621554b2c38.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to GET all moves of a game, in order
- [x] Add the ability to broadcast a forfeit to the room
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] GET all moves of a game when connecting
- [x] Play out the list of moves and load the final state of the board and gamestate when connecting
- [x] Add an exit button in the player palette that opens the PostGame component
- [x] Display a forfeit screen in the PostGame component if there is no winner
- [x] Send a PUT request to the server to update the game's winner if a game is forfeit
- [x] Broadcast a forfeit event after the PUT request
- [x] Display an Opponent Forfeit banner when a forfeit emit is received

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
