### ISSUE TITLE
MVP Feature: User can sign up

### ISSUE THREAD

**Issue by josephtnguyen** [josephtnguyen/straight-up-chess#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign up.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

From the home page, the user can choose to Sign Up.  This will take them to a signup form.  Once they have submitted appropriate credentials, the user can sign up their account.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/59109937/126219859-309a8b35-bf66-4fb3-9846-c63c4510919b.png)
![image](https://user-images.githubusercontent.com/59109937/126218853-6112c627-95a2-4130-8bf8-07cb7ca92fb2.png)
![image](https://user-images.githubusercontent.com/59109937/126218893-988a3776-67d8-4eaa-b78b-ee348b5b276c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Add a new 'users' table with 'userId', 'username', 'hashedPassword', 'createdAt' columns

### ☁️ Server

- [x] Update `server/index.js` to POST new users with hashedPasswords
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Add a sign-up button to the Home page that navigates to '#sign-up'
- [x] Create an AuthForm page that is rendered at '#sign-up'
- [x] Add username input
- [x] Add password input
- [x] Add a toggle to see the password
- [x] Add a sign up button
- [x] Add error handling for passwords less than 6 characters
- [x] Restrict username to 4-16 characters
- [x] POST the new user to the server when all criteria are met
- [x] Reject usernames that already exist

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
