### ISSUE TITLE
MVP Feature: User can sign in

### ISSUE THREAD

**Issue by josephtnguyen** [josephtnguyen/straight-up-chess#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign in.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can sign in, allowing their username to appear in-game instead of "Anonymous".  Incorrect credentials will be rejected.  refreshing the page should leave the user signed in.  Users can also sign out.  

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/59109937/126218986-66c5887f-1786-4e95-8713-c407c5c8185d.png)
![image](https://user-images.githubusercontent.com/59109937/126219016-ea926f69-e02b-4dfe-a031-9ce5a967e1b9.png)
![image](https://user-images.githubusercontent.com/59109937/126219038-75840479-0948-4a56-944a-d30fa49597e7.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to authorize a sign-in by responding with a token
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Add login button to Home page that navigates to the AuthForm page
- [x] Update the AuthForm to display login prompts
- [x] Add a link to the bottom of AuthForm for switching between login and signup
- [x] Make sure input errors in AuthForm are consistent for login
- [x] Create a handleSignIn method in the App component, and pass the method into AuthForm
- [x] Call handleSignIn when a successful sign-in occurs
- [x] Return to the Home page after a successful login
- [x] Add login to nav bar which changes to log out when signed in
- [x] Remove the sign-up and login buttons on the home page when signed in
- [x] Create a handleSignOut method in the App component
- [x] Pass the username as a context for the app
- [x] Apply the username when creating a new game
- [x] Apply the username when joining a post
- [x] Apply the username while playing a game
- [x] Automatically log in after signing up

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
